<?php
require_once __DIR__ . '/../bootstrap.php'; require_admin(); $pdo=admin_db(); $adminTitle='Banners';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$id=(int)($_POST['id']??0);$desktop=upload_admin_image('desktop_image','banners')??($_POST['current_desktop']??'');$mobile=upload_admin_image('mobile_image','banners')??($_POST['current_mobile']??'');$data=[':title'=>trim($_POST['title']),':subtitle'=>trim($_POST['subtitle']),':image_url'=>$desktop,':mobile_image_url'=>$mobile,':link_url'=>trim($_POST['link_url']),':sort_order'=>(int)$_POST['sort_order'],':is_active'=>(int)($_POST['is_active']??0)];if($id>0){$data[':id']=$id;$pdo->prepare('UPDATE banners SET title=:title,subtitle=:subtitle,image_url=:image_url,mobile_image_url=:mobile_image_url,link_url=:link_url,sort_order=:sort_order,is_active=:is_active WHERE id=:id')->execute($data);}else{$pdo->prepare('INSERT INTO banners (title,subtitle,image_url,mobile_image_url,link_url,sort_order,is_active) VALUES (:title,:subtitle,:image_url,:mobile_image_url,:link_url,:sort_order,:is_active)')->execute($data);}redirect_with(admin_url('banners/'),'Banner saved.');}
if(isset($_GET['delete'])){$pdo->prepare('DELETE FROM banners WHERE id=:id')->execute([':id'=>(int)$_GET['delete']]);redirect_with(admin_url('banners/'),'Banner deleted.');}
$edit=null;if(isset($_GET['edit'])){$s=$pdo->prepare('SELECT * FROM banners WHERE id=:id');$s->execute([':id'=>(int)$_GET['edit']]);$edit=$s->fetch();}$rows=$pdo->query('SELECT * FROM banners ORDER BY sort_order,id DESC')->fetchAll();require __DIR__.'/../header.php';
?>
<section class="panel"><div class="panel-head"><h2><?= $edit?'Edit':'Add'; ?> Banner</h2></div><form class="admin-form" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()); ?>"><input type="hidden" name="id" value="<?= e((string)($edit['id']??'')); ?>"><input type="hidden" name="current_desktop" value="<?= e((string)($edit['image_url']??'')); ?>"><input type="hidden" name="current_mobile" value="<?= e((string)($edit['mobile_image_url']??'')); ?>"><label>Banner Title<input name="title" value="<?= e((string)($edit['title']??'')); ?>" required></label><label>Subtitle<input name="subtitle" value="<?= e((string)($edit['subtitle']??'')); ?>"></label><label>Redirect URL<input name="link_url" value="<?= e((string)($edit['link_url']??'shop.php')); ?>"></label><label>Display Order<input type="number" name="sort_order" value="<?= e((string)($edit['sort_order']??0)); ?>"></label><label>Status<select name="is_active"><option value="1" <?= (int)($edit['is_active']??1)===1?'selected':''; ?>>Active</option><option value="0" <?= (int)($edit['is_active']??1)===0?'selected':''; ?>>Inactive</option></select></label><label>Desktop Image<input type="file" name="desktop_image" accept="image/*"></label><label>Mobile Image<input type="file" name="mobile_image" accept="image/*"></label><button class="admin-btn primary">Save Banner</button></form></section>
<section class="panel"><div class="table-wrap"><table><thead><tr><th>Image</th><th>Title</th><th>Order</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><?php if($row['image_url']): ?><img class="thumb" src="<?= e(public_image($row['image_url'])); ?>" alt=""><?php endif; ?></td><td><?= e($row['title']); ?><small><?= e($row['link_url']); ?></small></td><td><?= (int)$row['sort_order']; ?></td><td><span class="pill"><?= $row['is_active']?'Active':'Inactive'; ?></span></td><td><a href="?edit=<?= (int)$row['id']; ?>">Edit</a> <a class="danger-link" href="?delete=<?= (int)$row['id']; ?>" data-confirm>Delete</a></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php require __DIR__.'/../footer.php'; ?>
