<?php
require_once __DIR__ . '/../bootstrap.php'; require_admin(); $pdo=admin_db(); $adminTitle='Blogs';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$id=(int)($_POST['id']??0);$image=upload_admin_image('featured_image','blogs')??($_POST['current_image']??'');$data=[':title'=>trim($_POST['title']),':slug'=>trim($_POST['slug']),':excerpt'=>trim($_POST['excerpt']),':content'=>$_POST['content'],':seo_title'=>trim($_POST['seo_title']),':seo_description'=>trim($_POST['seo_description']),':image_url'=>$image,':status'=>$_POST['status'],':published_at'=>$_POST['published_at']?:date('Y-m-d')];if($id>0){$data[':id']=$id;$pdo->prepare('UPDATE blogs SET title=:title,slug=:slug,excerpt=:excerpt,content=:content,seo_title=:seo_title,seo_description=:seo_description,image_url=:image_url,status=:status,published_at=:published_at WHERE id=:id')->execute($data);}else{$pdo->prepare('INSERT INTO blogs (title,slug,excerpt,content,seo_title,seo_description,image_url,status,published_at) VALUES (:title,:slug,:excerpt,:content,:seo_title,:seo_description,:image_url,:status,:published_at)')->execute($data);}redirect_with(admin_url('blogs/'),'Blog saved.');}
if(isset($_GET['delete'])){$pdo->prepare('DELETE FROM blogs WHERE id=:id')->execute([':id'=>(int)$_GET['delete']]);redirect_with(admin_url('blogs/'),'Blog deleted.');}
$edit=null;if(isset($_GET['edit'])){$s=$pdo->prepare('SELECT * FROM blogs WHERE id=:id');$s->execute([':id'=>(int)$_GET['edit']]);$edit=$s->fetch();}$rows=$pdo->query('SELECT * FROM blogs ORDER BY published_at DESC,id DESC')->fetchAll();require __DIR__.'/../header.php';
?>
<section class="panel"><div class="panel-head"><h2><?= $edit?'Edit':'Create'; ?> Blog</h2></div><form class="admin-form product-form" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()); ?>"><input type="hidden" name="id" value="<?= e((string)($edit['id']??'')); ?>"><input type="hidden" name="current_image" value="<?= e((string)($edit['image_url']??'')); ?>"><label>Title<input name="title" value="<?= e((string)($edit['title']??'')); ?>" required></label><label>Slug<input name="slug" value="<?= e((string)($edit['slug']??'')); ?>" required></label><label>Status<select name="status"><option value="published" <?= ($edit['status']??'published')==='published'?'selected':''; ?>>Publish</option><option value="draft" <?= ($edit['status']??'')==='draft'?'selected':''; ?>>Draft</option></select></label><label>Publish Date<input type="date" name="published_at" value="<?= e((string)($edit['published_at']??date('Y-m-d'))); ?>"></label><label class="wide">Excerpt<textarea name="excerpt" rows="3"><?= e((string)($edit['excerpt']??'')); ?></textarea></label><label class="wide">Rich Text Content<textarea class="rich-editor" name="content" rows="9"><?= e((string)($edit['content']??'')); ?></textarea></label><label>SEO Title<input name="seo_title" value="<?= e((string)($edit['seo_title']??'')); ?>"></label><label>SEO Description<input name="seo_description" value="<?= e((string)($edit['seo_description']??'')); ?>"></label><label>Featured Image<input type="file" name="featured_image" accept="image/*"></label><button class="admin-btn primary">Save Blog</button></form></section>
<section class="panel"><div class="table-wrap"><table><thead><tr><th>Image</th><th>Title</th><th>Status</th><th>Date</th><th>Actions</th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><?php if($row['image_url']): ?><img class="thumb" src="<?= e(public_image($row['image_url'])); ?>" alt=""><?php endif; ?></td><td><?= e($row['title']); ?><small><?= e($row['slug']); ?></small></td><td><span class="pill"><?= e($row['status']); ?></span></td><td><?= e($row['published_at']); ?></td><td><a href="?edit=<?= (int)$row['id']; ?>">Edit</a> <a class="danger-link" href="?delete=<?= (int)$row['id']; ?>" data-confirm>Delete</a></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php require __DIR__.'/../footer.php'; ?>
