<?php
require_once __DIR__ . '/../bootstrap.php'; require_admin(); $pdo=admin_db(); $adminTitle='Settings';
$defaults=['website_name'=>'ZetaStyle','logo'=>'','favicon'=>'','contact_number'=>'','whatsapp_number'=>'','email'=>'','address'=>'','instagram'=>'','facebook'=>'','footer_text'=>'Premium custom printed clothing.','seo_title'=>'ZetaStyle','seo_description'=>'Premium custom printed clothing store.'];
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$logo=upload_admin_image('logo','settings')??($_POST['logo_current']??'');$favicon=upload_admin_image('favicon','settings')??($_POST['favicon_current']??'');foreach($defaults as $key=>$value){$val=$_POST[$key]??'';if($key==='logo')$val=$logo;if($key==='favicon')$val=$favicon;$stmt=$pdo->prepare('INSERT INTO settings (`setting_key`,`setting_value`) VALUES (:k,:v) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)');$stmt->execute([':k'=>$key,':v'=>$val]);}redirect_with(admin_url('settings/'),'Settings saved.');}
$settings=$defaults;foreach($pdo->query('SELECT setting_key,setting_value FROM settings') as $row)$settings[$row['setting_key']]=$row['setting_value'];require __DIR__.'/../header.php';
?>
<section class="panel"><div class="panel-head"><h2>Website Settings</h2></div><form class="admin-form product-form" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()); ?>"><input type="hidden" name="logo_current" value="<?= e($settings['logo']); ?>"><input type="hidden" name="favicon_current" value="<?= e($settings['favicon']); ?>">
<label>Website Name<input name="website_name" value="<?= e($settings['website_name']); ?>"></label><label>Contact Number<input name="contact_number" value="<?= e($settings['contact_number']); ?>"></label><label>WhatsApp Number<input name="whatsapp_number" value="<?= e($settings['whatsapp_number']); ?>"></label><label>Email<input name="email" value="<?= e($settings['email']); ?>"></label><label>Instagram<input name="instagram" value="<?= e($settings['instagram']); ?>"></label><label>Facebook<input name="facebook" value="<?= e($settings['facebook']); ?>"></label><label class="wide">Address<textarea name="address" rows="3"><?= e($settings['address']); ?></textarea></label><label class="wide">Footer Text<textarea name="footer_text" rows="3"><?= e($settings['footer_text']); ?></textarea></label><label>Logo<input type="file" name="logo" accept="image/*"></label><label>Favicon<input type="file" name="favicon" accept="image/*"></label><label>SEO Title<input name="seo_title" value="<?= e($settings['seo_title']); ?>"></label><label>SEO Description<input name="seo_description" value="<?= e($settings['seo_description']); ?>"></label><button class="admin-btn primary">Save Settings</button></form></section>
<?php require __DIR__.'/../footer.php'; ?>
